### ISSUE TITLE
Not getting reward after completion of thread 

### ISSUE THREAD

**Issue by oblansundar** [sau412/microgrid#5]
Hi,

I am using the website - microgrid - https://microgrid.arikado.ru/ and when I use my account in different systems (with different IP), I am not getting the reward.

Is there any limitation to use this microgrid in only one IP? I guess its not so.

My user account in microgrid is naruto93. Could you please kindly check and let me know the reason?

Thanks.

**Comment by sau412** [comment]
Hi. Different systems with different IPs should account equally. You can complete couple of units from one PC, then couple of units from another and check results.

**Comment by oblansundar** [comment]
Sure, Thank you for the reply. It works now.
